/** Declaration file generated by dts-gen */

export function decode (buf: any, offset?: any): any;

export function encode (num: any, buf?: any, offset?: any): any;

export function encodingLength (): any;
