/**
 * Description:
 *  This script demonstrates a transaction validated by an asc signed by multisig account with a threshold of 2
    User saves the signed logic in assets/ which is extracted and used here.
*/
const { transferAlgo } = require("./common");
const { transferMicroAlgos, createMsigAddress } = require("algob");

async function run(runtimeEnv, deployer) {
  const masterAccount = deployer.accountsByName.get("master-account")
  const goldOwnerAccount = deployer.accountsByName.get("gold-owner-account");
  const johnAccount = deployer.accountsByName.get("john-account");
  const bobAccount = deployer.accountsByName.get("bob-account");
  
  //Generate multi signature account hash 
  const addrs =  [goldOwnerAccount.addr, johnAccount.addr, bobAccount.addr]  // you can replace these addresses with your custom addrs for multisig account.
  const [mparams, multsigaddr] = createMsigAddress(1, 2, addrs);   // passing (version, threshold, address list)
 
  //Funding multisignature account
  await transferMicroAlgos(deployer, masterAccount, multsigaddr, 10000000, {note: "Funding multisig account"});
  
  // below we can also use an lsgi using a decompiled file generated by goal (goal clerk compile -D <path_to_file>)
  // const lsig = await deployer.loadMultiSig("sample-text-asc.msig", []);  

  const lsig = await deployer.loadBinaryMultiSig("sample-raw-asc.msig");  

  // Transaction PASSES
  await transferAlgo(deployer, { addr: multsigaddr }, bobAccount.addr, 20, lsig);

  // Transaction FAIL - according to teal logic, amount should be <= 100
  await transferAlgo(deployer, { addr: multsigaddr }, bobAccount.addr, 200, lsig);
}

module.exports = { default: run }
