# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
# starters: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Run tests on push

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  job1:
    uses: ./.github/workflows/reusableWorkflow.yaml

  job2:
    runs-on: ubuntu-20.04
    needs: job1
    steps:
      - name: Execute algob tests
        run: cd packages/algob && pipenv run yarn test
