# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
# starters: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Run tests on push

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  job1:
    call-workflow-2-in-local-repo:
      uses: ./.github/workflows/reusableWorkflow.yaml
      steps:
        - name: Execute algob tests
            run: cd packages/algob && pipenv run yarn test
