# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
# starters: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Run tests on push

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  # algob-tests:
  #   uses: ./.github/workflows/reusableWorkflow.yaml
  #   package:
  #     name: algob
  #     command: cd packages/algob && yarn test

  # web-tests:
  #   uses: ./.github/workflows/reusableWorkflow.yaml
  #   package:
  #     name: web
  #     command: cd packages/web && yarn test

  runtime-tests:
    name: Runtime 
    uses: ./.github/workflows/reusableWorkflow.yaml
    with:
      name: runtime
      command: cd packages/runtime && yarn test
