name: Run examples on push

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  run-examples:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.15.4'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install python dependencies
        run: python -m pip install pipenv
      - run: pipenv sync
      - name: Install dependencies
        run: pipenv run yarn install
      - run: yarn build
      - run: cd packages/algob && yarn link && cd .. && cd ..

      - name: Setup Network
        run: |
            sudo apt-get update && sudo apt-get install -y gnupg2 curl software-properties-common
            curl -O https://releases.algorand.com/key.pub && sudo apt-key add key.pub
            sudo add-apt-repository "deb [arch=amd64] https://releases.algorand.com/deb/ stable main"
            sudo apt-get update && sudo apt-get install -y algorand
            cd infrastructure && make setup-private-net


      - name: Setup algob
        run: yarn link @algo-builder/algob  && chmod +x /usr/local/bin/algob

      - name: Example ASA
        working-directory: ./examples/asa
        run: |
            pipenv run yarn algob deploy
            pipenv run yarn algob run scripts/transfer/gold-contract-sc.js
            pipenv run yarn algob run scripts/transfer/gold-delegated-lsig.js
            pipenv run yarn algob run scripts/transfer/gold-to-john.js
            pipenv run yarn algob run scripts/transfer/master-fund-john.js
            pipenv run yarn algob run scripts/transfer/tesla-to-john.js

      - name: Example bond token
        working-directory: ./examples/bond
        run: |
          pipenv run yarn algob deploy
          pipenv run yarn algob run scripts/run/run.js

      - name: Example crowdfunding
        working-directory: ./examples/crowdfunding
        run: |
          pipenv run yarn algob deploy
          pipenv run yarn algob run scripts/transfer/donate.js

      - name: Example htlc-pyteal-ts
        working-directory: ./examples/htlc-pyteal-ts
        run: |
          pipenv run yarn algob deploy
          pipenv run yarn algob run scripts/withdraw/htlc-withdraw.ts

      - name: Example multisig
        run: cd examples/multisig && pipenv run yarn algob deploy

      - name: Example nft
        working-directory: ./examples/nft
        run: |
          pipenv run yarn algob deploy
          pipenv run yarn algob run scripts/transfer/create-transfer-nft.js

      - name: Example permissioned-token
        run: cd examples/permissioned-token && pipenv run yarn algob deploy

      - name: Example permissioned-token-freezing
        working-directory: ./examples/permissioned-token-freezing
        run: |
          pipenv run yarn algob deploy
          pipenv run yarn algob run scripts/transfer/set-clear-level.js
          pipenv run yarn algob run scripts/transfer/transfer-asset.js

      - name: Example permissioned-voting
        working-directory: ./examples/permissioned-voting
        run: |
          pipenv run yarn algob deploy
          pipenv run yarn algob run scripts/vote/vote.js
          pipenv run yarn algob run scripts/vote/result.js

      - name: Example ref-templates
        run: cd examples/ref-templates && pipenv run yarn algob deploy

      - name: Example stateful-counter
        working-directory: ./examples/stateful-counter
        run: |
          pipenv run yarn algob deploy
          pipenv run yarn algob run scripts/interaction/call_application.js