# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
# starters: https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Run tests on push

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16"
      #          cache: "yarn"
      - name: Set yarn version
        run: yarn set version stable
      - name: Yarn version check
        run: yarn --version
      - name: Install dependencies
        run: yarn install
      - name: Execute lint
        run: yarn lint
      - run: yarn build

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install python dependencies
        run: python -m pip install pipenv
      - run: pipenv sync

      - name: Execute tests
        run: pipenv run yarn test
