name: Run tests on push
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn install
      - name: Execute lint
        run: yarn lint
      - name: Execute tests
        run: yarn test

