name: PR tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Print dir
        run: pwd && ls
      - name: Install dependencies
        run: yarn install
      - name: Execute tests
        run: yarn test

